-- procedure para gerar o relatorio de saldo do cliente de acordo com o periodo passado

CREATE OR REPLACE PROCEDURE REPORT_CLIENT_BALANCE_BY_PERIOD (
    P_CLIENT_ID IN RAW,
    P_DATA_INICIO IN DATE,
    P_DATA_FIM IN DATE,
    P_CLIENTE_NOME OUT VARCHAR2,
    P_DATA_CADASTRO OUT TIMESTAMP,
    P_ENDERECO OUT VARCHAR2,
    P_MOV_CREDITO OUT NUMBER,
    P_MOV_DEBITO OUT NUMBER,
    P_TOTAL_MOVIMENTACOES OUT NUMBER,
    P_VALOR_PAGO_MOVIMENTACOES OUT NUMBER,
    P_SALDO_INICIAL OUT NUMBER,
    P_SALDO_ATUAL OUT NUMBER
)
AS
BEGIN
    SELECT NAME, CREATED_AT
    INTO P_CLIENTE_NOME, P_DATA_CADASTRO
    FROM CLIENT
    WHERE ID = P_CLIENT_ID;
    
    SELECT STREET || ', ' || ADDRESS_NUMBER || ', ' || NEIGHBORHOOD || ', ' || CITY || ', ' || STATE || ', ' || ZIP_CODE
    INTO P_ENDERECO
    FROM ADDRESS
    WHERE CLIENT_ID = P_CLIENT_ID;
    
    SELECT INITIAL_BALANCE
    INTO P_SALDO_INICIAL
    FROM ACCOUNT
    WHERE CLIENT_ID = P_CLIENT_ID;
    
    -- verifica a quantidade de cada tipo de movimentação no periodo informado
    SELECT COUNT(CASE WHEN OPERATION_TYPE = 'C' THEN 1 END),
           COUNT(CASE WHEN OPERATION_TYPE = 'D' THEN 1 END),
           COUNT(*)
    INTO P_MOV_CREDITO, P_MOV_DEBITO, P_TOTAL_MOVIMENTACOES
    FROM TRANSACTION T
    WHERE T.ACCOUNT_ID IN (SELECT A.ID FROM ACCOUNT A WHERE A.CLIENT_ID = P_CLIENT_ID)
    AND T.CREATED_AT BETWEEN P_DATA_INICIO AND P_DATA_FIM;
    
    -- calcula o saldo de acordo com o periodo informado
    SELECT NVL(SUM(CASE WHEN OPERATION_TYPE = 'C' THEN AMOUNT ELSE -AMOUNT END), 0) + P_SALDO_INICIAL
    INTO P_SALDO_ATUAL
    FROM TRANSACTION T
    WHERE T.ACCOUNT_ID IN (SELECT A.ID FROM ACCOUNT A WHERE A.CLIENT_ID = P_CLIENT_ID)
    AND T.CREATED_AT BETWEEN P_DATA_INICIO AND P_DATA_FIM;
    
    IF P_TOTAL_MOVIMENTACOES <= 10 THEN
        P_VALOR_PAGO_MOVIMENTACOES := P_TOTAL_MOVIMENTACOES * 1.00;
    ELSIF P_TOTAL_MOVIMENTACOES <= 20 THEN
        P_VALOR_PAGO_MOVIMENTACOES := P_TOTAL_MOVIMENTACOES * 0.75;
    ELSE
        P_VALOR_PAGO_MOVIMENTACOES := P_TOTAL_MOVIMENTACOES * 0.50;
    END IF;
END;